In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm

In [5]:
# Loading datasets
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train = train.drop(columns = 'Unnamed: 0')
train.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,5,5,18,1,1,?,...,No,No,No,No,No,No,No,No,No,-1
1,64410,86047875,AfricanAmerican,Female,25,1,1,7,2,?,...,No,No,No,No,No,No,No,No,Yes,-1
2,500364,82442376,Caucasian,Male,35,1,1,7,2,?,...,No,Up,No,No,No,No,No,Ch,Yes,-1
3,35754,82637451,Caucasian,Male,55,1,1,1,3,?,...,No,Steady,No,No,No,No,No,No,Yes,-1
4,55842,84259809,Caucasian,Male,65,3,1,1,4,?,...,No,Steady,No,No,No,No,No,Ch,Yes,-1

In [ ]:
# Changing the values of the response variable
train['readmitted'] = train['readmitted'].replace(-1, 0)
test['readmitted'] = test['readmitted'].replace(-1, 0)